// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SharpPulsar.Admin.Admin.Models
{
    public class JsonGeneratorBase
    {

        /// <summary>
        /// </summary>
        [JsonPropertyName("codec")]
        public ObjectCodec Codec { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("currentValue")]
        public object CurrentValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("featureMask")]
        public int? FeatureMask { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("formatFeatures")]
        public int? FormatFeatures { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("outputContext")]
        public JsonStreamContext OutputContext { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("outputTarget")]
        public object OutputTarget { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("highestEscapedChar")]
        public int? HighestEscapedChar { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("outputBuffered")]
        public int? OutputBuffered { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("closed")]
        public bool? Closed { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("prettyPrinter")]
        public object PrettyPrinter { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("characterEscapes")]
        public CharacterEscapes CharacterEscapes { get; set; }

        /// <summary>
        /// </summary>
        [JsonPropertyName("schema")]
        public FormatSchema Schema { get; set; }

    }
}