// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SnapshotMessages.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Akka.Persistence.Serialization.Proto.Msg {

  /// <summary>Holder for reflection information generated from SnapshotMessages.proto</summary>
  internal static partial class SnapshotMessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for SnapshotMessages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SnapshotMessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZTbmFwc2hvdE1lc3NhZ2VzLnByb3RvEihBa2thLlBlcnNpc3RlbmNlLlNl",
            "cmlhbGl6YXRpb24uUHJvdG8uTXNnGg90aW1lc3RhbXAucHJvdG8iuQEKD1Nu",
            "YXBzaG90TWVzc2FnZRIVCg1wZXJzaXN0ZW5jZUlkGAEgASgJEhIKCnNlcXVl",
            "bmNlTnIYAiABKAMSLQoJdGltZVN0YW1wGAMgASgLMhouZ29vZ2xlLnByb3Rv",
            "YnVmLlRpbWVzdGFtcBJMCgdwYXlsb2FkGAQgASgLMjsuQWtrYS5QZXJzaXN0",
            "ZW5jZS5TZXJpYWxpemF0aW9uLlByb3RvLk1zZy5QZXJzaXN0ZW50UGF5bG9h",
            "ZCJTChFQZXJzaXN0ZW50UGF5bG9hZBIUCgxzZXJpYWxpemVySWQYASABKAUS",
            "DwoHcGF5bG9hZBgCIAEoDBIXCg9wYXlsb2FkTWFuaWZlc3QYAyABKAxiBnBy",
            "b3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Persistence.Serialization.Proto.Msg.SnapshotMessage), global::Akka.Persistence.Serialization.Proto.Msg.SnapshotMessage.Parser, new[]{ "PersistenceId", "SequenceNr", "TimeStamp", "Payload" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Akka.Persistence.Serialization.Proto.Msg.PersistentPayload), global::Akka.Persistence.Serialization.Proto.Msg.PersistentPayload.Parser, new[]{ "SerializerId", "Payload", "PayloadManifest" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  internal sealed partial class SnapshotMessage : pb::IMessage<SnapshotMessage> {
    private static readonly pb::MessageParser<SnapshotMessage> _parser = new pb::MessageParser<SnapshotMessage>(() => new SnapshotMessage());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SnapshotMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Persistence.Serialization.Proto.Msg.SnapshotMessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SnapshotMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SnapshotMessage(SnapshotMessage other) : this() {
      persistenceId_ = other.persistenceId_;
      sequenceNr_ = other.sequenceNr_;
      TimeStamp = other.timeStamp_ != null ? other.TimeStamp.Clone() : null;
      Payload = other.payload_ != null ? other.Payload.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SnapshotMessage Clone() {
      return new SnapshotMessage(this);
    }

    /// <summary>Field number for the "persistenceId" field.</summary>
    public const int PersistenceIdFieldNumber = 1;
    private string persistenceId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PersistenceId {
      get { return persistenceId_; }
      set {
        persistenceId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sequenceNr" field.</summary>
    public const int SequenceNrFieldNumber = 2;
    private long sequenceNr_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long SequenceNr {
      get { return sequenceNr_; }
      set {
        sequenceNr_ = value;
      }
    }

    /// <summary>Field number for the "timeStamp" field.</summary>
    public const int TimeStampFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timeStamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 4;
    private global::Akka.Persistence.Serialization.Proto.Msg.PersistentPayload payload_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Akka.Persistence.Serialization.Proto.Msg.PersistentPayload Payload {
      get { return payload_; }
      set {
        payload_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SnapshotMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SnapshotMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PersistenceId != other.PersistenceId) return false;
      if (SequenceNr != other.SequenceNr) return false;
      if (!object.Equals(TimeStamp, other.TimeStamp)) return false;
      if (!object.Equals(Payload, other.Payload)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PersistenceId.Length != 0) hash ^= PersistenceId.GetHashCode();
      if (SequenceNr != 0L) hash ^= SequenceNr.GetHashCode();
      if (timeStamp_ != null) hash ^= TimeStamp.GetHashCode();
      if (payload_ != null) hash ^= Payload.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PersistenceId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PersistenceId);
      }
      if (SequenceNr != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(SequenceNr);
      }
      if (timeStamp_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TimeStamp);
      }
      if (payload_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Payload);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PersistenceId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PersistenceId);
      }
      if (SequenceNr != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(SequenceNr);
      }
      if (timeStamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TimeStamp);
      }
      if (payload_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Payload);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SnapshotMessage other) {
      if (other == null) {
        return;
      }
      if (other.PersistenceId.Length != 0) {
        PersistenceId = other.PersistenceId;
      }
      if (other.SequenceNr != 0L) {
        SequenceNr = other.SequenceNr;
      }
      if (other.timeStamp_ != null) {
        if (timeStamp_ == null) {
          timeStamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        TimeStamp.MergeFrom(other.TimeStamp);
      }
      if (other.payload_ != null) {
        if (payload_ == null) {
          payload_ = new global::Akka.Persistence.Serialization.Proto.Msg.PersistentPayload();
        }
        Payload.MergeFrom(other.Payload);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            PersistenceId = input.ReadString();
            break;
          }
          case 16: {
            SequenceNr = input.ReadInt64();
            break;
          }
          case 26: {
            if (timeStamp_ == null) {
              timeStamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(timeStamp_);
            break;
          }
          case 34: {
            if (payload_ == null) {
              payload_ = new global::Akka.Persistence.Serialization.Proto.Msg.PersistentPayload();
            }
            input.ReadMessage(payload_);
            break;
          }
        }
      }
    }

  }

  internal sealed partial class PersistentPayload : pb::IMessage<PersistentPayload> {
    private static readonly pb::MessageParser<PersistentPayload> _parser = new pb::MessageParser<PersistentPayload>(() => new PersistentPayload());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PersistentPayload> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Akka.Persistence.Serialization.Proto.Msg.SnapshotMessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersistentPayload() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersistentPayload(PersistentPayload other) : this() {
      serializerId_ = other.serializerId_;
      payload_ = other.payload_;
      payloadManifest_ = other.payloadManifest_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PersistentPayload Clone() {
      return new PersistentPayload(this);
    }

    /// <summary>Field number for the "serializerId" field.</summary>
    public const int SerializerIdFieldNumber = 1;
    private int serializerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int SerializerId {
      get { return serializerId_; }
      set {
        serializerId_ = value;
      }
    }

    /// <summary>Field number for the "payload" field.</summary>
    public const int PayloadFieldNumber = 2;
    private pb::ByteString payload_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Payload {
      get { return payload_; }
      set {
        payload_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "payloadManifest" field.</summary>
    public const int PayloadManifestFieldNumber = 3;
    private pb::ByteString payloadManifest_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString PayloadManifest {
      get { return payloadManifest_; }
      set {
        payloadManifest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PersistentPayload);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PersistentPayload other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SerializerId != other.SerializerId) return false;
      if (Payload != other.Payload) return false;
      if (PayloadManifest != other.PayloadManifest) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (SerializerId != 0) hash ^= SerializerId.GetHashCode();
      if (Payload.Length != 0) hash ^= Payload.GetHashCode();
      if (PayloadManifest.Length != 0) hash ^= PayloadManifest.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (SerializerId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SerializerId);
      }
      if (Payload.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Payload);
      }
      if (PayloadManifest.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(PayloadManifest);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (SerializerId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SerializerId);
      }
      if (Payload.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Payload);
      }
      if (PayloadManifest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PayloadManifest);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PersistentPayload other) {
      if (other == null) {
        return;
      }
      if (other.SerializerId != 0) {
        SerializerId = other.SerializerId;
      }
      if (other.Payload.Length != 0) {
        Payload = other.Payload;
      }
      if (other.PayloadManifest.Length != 0) {
        PayloadManifest = other.PayloadManifest;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            SerializerId = input.ReadInt32();
            break;
          }
          case 18: {
            Payload = input.ReadBytes();
            break;
          }
          case 26: {
            PayloadManifest = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
