<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Akka" />
    <PackageReference Include="OpenTelemetry.Api" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharpPulsar.Shared\SharpPulsar.Shared.csproj" />
    <ProjectReference Include="..\SharpPulsar.TimeUnit\SharpPulsar.TimeUnit.csproj" />
  </ItemGroup>

</Project>
