<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="App.Metrics.Concurrency" />
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SharpPulsar.TimeUnit\SharpPulsar.TimeUnit.csproj" />
  </ItemGroup>

</Project>

