// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AllocatorStats
    {
        /// <summary>
        /// Initializes a new instance of the AllocatorStats class.
        /// </summary>
        public AllocatorStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AllocatorStats class.
        /// </summary>
        public AllocatorStats(int? numDirectArenas = default(int?), int? numHeapArenas = default(int?), int? numThreadLocalCaches = default(int?), int? normalCacheSize = default(int?), int? smallCacheSize = default(int?), int? tinyCacheSize = default(int?), IList<PoolArenaStats> directArenas = default(IList<PoolArenaStats>), IList<PoolArenaStats> heapArenas = default(IList<PoolArenaStats>))
        {
            NumDirectArenas = numDirectArenas;
            NumHeapArenas = numHeapArenas;
            NumThreadLocalCaches = numThreadLocalCaches;
            NormalCacheSize = normalCacheSize;
            SmallCacheSize = smallCacheSize;
            TinyCacheSize = tinyCacheSize;
            DirectArenas = directArenas;
            HeapArenas = heapArenas;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numDirectArenas")]
        public int? NumDirectArenas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numHeapArenas")]
        public int? NumHeapArenas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numThreadLocalCaches")]
        public int? NumThreadLocalCaches { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "normalCacheSize")]
        public int? NormalCacheSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "smallCacheSize")]
        public int? SmallCacheSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tinyCacheSize")]
        public int? TinyCacheSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "directArenas")]
        public IList<PoolArenaStats> DirectArenas { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "heapArenas")]
        public IList<PoolArenaStats> HeapArenas { get; set; }

    }
}
