// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The auto failover policy configuration data
    /// </summary>
    public partial class AutoFailoverPolicyData
    {
        /// <summary>
        /// Initializes a new instance of the AutoFailoverPolicyData class.
        /// </summary>
        public AutoFailoverPolicyData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AutoFailoverPolicyData class.
        /// </summary>
        /// <param name="policyType">The auto failover policy type. Possible
        /// values include: 'min_available'</param>
        /// <param name="parameters">The parameters applied to the auto
        /// failover policy specified by `policy_type`.
        /// The parameters for 'min_available' are :
        /// - 'min_limit': the limit of minimal number of available brokers in
        /// primary group before auto failover
        /// - 'usage_threshold': the resource usage threshold. If the usage of
        /// a broker is beyond this value, it would be marked as unavailable
        /// </param>
        public AutoFailoverPolicyData(string policyType = default(string), IDictionary<string, string> parameters = default(IDictionary<string, string>))
        {
            PolicyType = policyType;
            Parameters = parameters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the auto failover policy type. Possible values
        /// include: 'min_available'
        /// </summary>
        [JsonProperty(PropertyName = "policy_type")]
        public string PolicyType { get; set; }

        /// <summary>
        /// Gets or sets the parameters applied to the auto failover policy
        /// specified by `policy_type`.
        /// The parameters for 'min_available' are :
        /// - 'min_limit': the limit of minimal number of available brokers in
        /// primary group before auto failover
        /// - 'usage_threshold': the resource usage threshold. If the usage of
        /// a broker is beyond this value, it would be marked as unavailable
        ///
        /// </summary>
        [JsonProperty(PropertyName = "parameters")]
        public IDictionary<string, string> Parameters { get; set; }

    }
}
