// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ConsumerStats
    {
        /// <summary>
        /// Initializes a new instance of the ConsumerStats class.
        /// </summary>
        public ConsumerStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ConsumerStats class.
        /// </summary>
        public ConsumerStats(double? msgRateOut = default(double?), double? msgThroughputOut = default(double?), double? msgRateRedeliver = default(double?), string consumerName = default(string), int? availablePermits = default(int?), int? unackedMessages = default(int?), bool? blockedConsumerOnUnackedMsgs = default(bool?), IDictionary<string, string> metadata = default(IDictionary<string, string>), string address = default(string), string connectedSince = default(string), string clientVersion = default(string))
        {
            MsgRateOut = msgRateOut;
            MsgThroughputOut = msgThroughputOut;
            MsgRateRedeliver = msgRateRedeliver;
            ConsumerName = consumerName;
            AvailablePermits = availablePermits;
            UnackedMessages = unackedMessages;
            BlockedConsumerOnUnackedMsgs = blockedConsumerOnUnackedMsgs;
            Metadata = metadata;
            Address = address;
            ConnectedSince = connectedSince;
            ClientVersion = clientVersion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msgRateOut")]
        public double? MsgRateOut { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msgThroughputOut")]
        public double? MsgThroughputOut { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msgRateRedeliver")]
        public double? MsgRateRedeliver { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "consumerName")]
        public string ConsumerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "availablePermits")]
        public int? AvailablePermits { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unackedMessages")]
        public int? UnackedMessages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "blockedConsumerOnUnackedMsgs")]
        public bool? BlockedConsumerOnUnackedMsgs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public IDictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connectedSince")]
        public string ConnectedSince { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientVersion")]
        public string ClientVersion { get; set; }

    }
}
