// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DispatchRate
    {
        /// <summary>
        /// Initializes a new instance of the DispatchRate class.
        /// </summary>
        public DispatchRate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DispatchRate class.
        /// </summary>
        public DispatchRate(int? dispatchThrottlingRateInMsg = default(int?), long? dispatchThrottlingRateInByte = default(long?), bool? relativeToPublishRate = default(bool?), int? ratePeriodInSecond = default(int?))
        {
            DispatchThrottlingRateInMsg = dispatchThrottlingRateInMsg;
            DispatchThrottlingRateInByte = dispatchThrottlingRateInByte;
            RelativeToPublishRate = relativeToPublishRate;
            RatePeriodInSecond = ratePeriodInSecond;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dispatchThrottlingRateInMsg")]
        public int? DispatchThrottlingRateInMsg { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dispatchThrottlingRateInByte")]
        public long? DispatchThrottlingRateInByte { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relativeToPublishRate")]
        public bool? RelativeToPublishRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ratePeriodInSecond")]
        public int? RatePeriodInSecond { get; set; }

    }
}
