// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetSchemaResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetSchemaResponse class.
        /// </summary>
        public GetSchemaResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetSchemaResponse class.
        /// </summary>
        /// <param name="type">Possible values include: 'NONE', 'STRING',
        /// 'JSON', 'PROTOBUF', 'AVRO', 'BOOLEAN', 'INT8', 'INT16', 'INT32',
        /// 'INT64', 'FLOAT', 'DOUBLE', 'DATE', 'TIME', 'TIMESTAMP',
        /// 'KEY_VALUE', 'BYTES', 'AUTO', 'AUTO_CONSUME',
        /// 'AUTO_PUBLISH'</param>
        public GetSchemaResponse(long? version = default(long?), string type = default(string), long? timestamp = default(long?), string data = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Version = version;
            Type = type;
            Timestamp = timestamp;
            Data = data;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public long? Version { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'NONE', 'STRING', 'JSON',
        /// 'PROTOBUF', 'AVRO', 'BOOLEAN', 'INT8', 'INT16', 'INT32', 'INT64',
        /// 'FLOAT', 'DOUBLE', 'DATE', 'TIME', 'TIMESTAMP', 'KEY_VALUE',
        /// 'BYTES', 'AUTO', 'AUTO_CONSUME', 'AUTO_PUBLISH'
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public long? Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public string Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

    }
}
