// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;

    public partial class AdminMessageId
    {
        /// <summary>
        /// Initializes a new instance of the MessageIdImpl class.
        /// </summary>
        public AdminMessageId()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the MessageIdImpl class.
        /// </summary>
        public AdminMessageId(long? ledgerId = default(long?), long? entryId = default(long?), int? partitionIndex = default(int?))
        {
            LedgerId = ledgerId;
            EntryId = entryId;
            PartitionIndex = partitionIndex;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ledgerId")]
        public long? LedgerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entryId")]
        public long? EntryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "partitionIndex")]
        public int? PartitionIndex { get; set; }

    }
}