// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The data of namespace isolation configuration
    /// </summary>
    public partial class NamespaceIsolationData
    {
        /// <summary>
        /// Initializes a new instance of the NamespaceIsolationData class.
        /// </summary>
        public NamespaceIsolationData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NamespaceIsolationData class.
        /// </summary>
        /// <param name="namespaces">The list of namespaces to apply this
        /// namespace isolation data</param>
        /// <param name="primary">The list of secondary brokers for serving the
        /// list of namespaces in this isolation policy</param>
        /// <param name="autoFailoverPolicy">The data of auto-failover policy
        /// configuration</param>
        public NamespaceIsolationData(IList<string> namespaces = default(IList<string>), IList<string> primary = default(IList<string>), AutoFailoverPolicyData autoFailoverPolicy = default(AutoFailoverPolicyData))
        {
            Namespaces = namespaces;
            Primary = primary;
            AutoFailoverPolicy = autoFailoverPolicy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the list of namespaces to apply this namespace
        /// isolation data
        /// </summary>
        [JsonProperty(PropertyName = "namespaces")]
        public IList<string> Namespaces { get; set; }

        /// <summary>
        /// Gets or sets the list of secondary brokers for serving the list of
        /// namespaces in this isolation policy
        /// </summary>
        [JsonProperty(PropertyName = "primary")]
        public IList<string> Primary { get; set; }

        /// <summary>
        /// Gets or sets the data of auto-failover policy configuration
        /// </summary>
        [JsonProperty(PropertyName = "auto_failover_policy")]
        public AutoFailoverPolicyData AutoFailoverPolicy { get; set; }

    }
}
