// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OffloadProcessStatus
    {
        /// <summary>
        /// Initializes a new instance of the OffloadProcessStatus class.
        /// </summary>
        public OffloadProcessStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OffloadProcessStatus class.
        /// </summary>
        /// <param name="status">Possible values include: 'NOT_RUN', 'RUNNING',
        /// 'SUCCESS', 'ERROR'</param>
        public OffloadProcessStatus(string status = default(string), string lastError = default(string), AdminMessageId firstUnoffloadedAdminMessage = default(AdminMessageId))
        {
            Status = status;
            LastError = lastError;
            FirstUnoffloadedAdminMessage = firstUnoffloadedAdminMessage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'NOT_RUN', 'RUNNING',
        /// 'SUCCESS', 'ERROR'
        /// </summary>
        [JsonProperty(PropertyName = "status")]
        public string Status { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastError")]
        public string LastError { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstUnoffloadedMessage")]
        public AdminMessageId FirstUnoffloadedAdminMessage { get; set; }

    }
}
