// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PendingBookieOpsStats
    {
        /// <summary>
        /// Initializes a new instance of the PendingBookieOpsStats class.
        /// </summary>
        public PendingBookieOpsStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PendingBookieOpsStats class.
        /// </summary>
        public PendingBookieOpsStats(long? dataLedgerOpenOp = default(long?), long? dataLedgerCloseOp = default(long?), long? dataLedgerCreateOp = default(long?), long? dataLedgerDeleteOp = default(long?), long? cursorLedgerOpenOp = default(long?), long? cursorLedgerCloseOp = default(long?), long? cursorLedgerCreateOp = default(long?), long? cursorLedgerDeleteOp = default(long?))
        {
            DataLedgerOpenOp = dataLedgerOpenOp;
            DataLedgerCloseOp = dataLedgerCloseOp;
            DataLedgerCreateOp = dataLedgerCreateOp;
            DataLedgerDeleteOp = dataLedgerDeleteOp;
            CursorLedgerOpenOp = cursorLedgerOpenOp;
            CursorLedgerCloseOp = cursorLedgerCloseOp;
            CursorLedgerCreateOp = cursorLedgerCreateOp;
            CursorLedgerDeleteOp = cursorLedgerDeleteOp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataLedgerOpenOp")]
        public long? DataLedgerOpenOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataLedgerCloseOp")]
        public long? DataLedgerCloseOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataLedgerCreateOp")]
        public long? DataLedgerCreateOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataLedgerDeleteOp")]
        public long? DataLedgerDeleteOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursorLedgerOpenOp")]
        public long? CursorLedgerOpenOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursorLedgerCloseOp")]
        public long? CursorLedgerCloseOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursorLedgerCreateOp")]
        public long? CursorLedgerCreateOp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursorLedgerDeleteOp")]
        public long? CursorLedgerDeleteOp { get; set; }

    }
}
