// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PoolChunkListStats
    {
        /// <summary>
        /// Initializes a new instance of the PoolChunkListStats class.
        /// </summary>
        public PoolChunkListStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PoolChunkListStats class.
        /// </summary>
        public PoolChunkListStats(int? minUsage = default(int?), int? maxUsage = default(int?), IList<PoolChunkStats> chunks = default(IList<PoolChunkStats>))
        {
            MinUsage = minUsage;
            MaxUsage = maxUsage;
            Chunks = chunks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minUsage")]
        public int? MinUsage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxUsage")]
        public int? MaxUsage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chunks")]
        public IList<PoolChunkStats> Chunks { get; set; }

    }
}
