// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PoolSubpageStats
    {
        /// <summary>
        /// Initializes a new instance of the PoolSubpageStats class.
        /// </summary>
        public PoolSubpageStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PoolSubpageStats class.
        /// </summary>
        public PoolSubpageStats(int? maxNumElements = default(int?), int? numAvailable = default(int?), int? elementSize = default(int?), int? pageSize = default(int?))
        {
            MaxNumElements = maxNumElements;
            NumAvailable = numAvailable;
            ElementSize = elementSize;
            PageSize = pageSize;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "maxNumElements")]
        public int? MaxNumElements { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numAvailable")]
        public int? NumAvailable { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elementSize")]
        public int? ElementSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pageSize")]
        public int? PageSize { get; set; }

    }
}
