// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PoolArenaStats
    {
        /// <summary>
        /// Initializes a new instance of the PoolArenaStats class.
        /// </summary>
        public PoolArenaStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PoolArenaStats class.
        /// </summary>
        public PoolArenaStats(int? numTinySubpages = default(int?), int? numSmallSubpages = default(int?), int? numChunkLists = default(int?), IList<PoolSubpageStats> tinySubpages = default(IList<PoolSubpageStats>), IList<PoolSubpageStats> smallSubpages = default(IList<PoolSubpageStats>), IList<PoolChunkListStats> chunkLists = default(IList<PoolChunkListStats>), long? numAllocations = default(long?), long? numTinyAllocations = default(long?), long? numSmallAllocations = default(long?), long? numNormalAllocations = default(long?), long? numHugeAllocations = default(long?), long? numDeallocations = default(long?), long? numTinyDeallocations = default(long?), long? numSmallDeallocations = default(long?), long? numNormalDeallocations = default(long?), long? numHugeDeallocations = default(long?), long? numActiveAllocations = default(long?), long? numActiveTinyAllocations = default(long?), long? numActiveSmallAllocations = default(long?), long? numActiveNormalAllocations = default(long?), long? numActiveHugeAllocations = default(long?))
        {
            NumTinySubpages = numTinySubpages;
            NumSmallSubpages = numSmallSubpages;
            NumChunkLists = numChunkLists;
            TinySubpages = tinySubpages;
            SmallSubpages = smallSubpages;
            ChunkLists = chunkLists;
            NumAllocations = numAllocations;
            NumTinyAllocations = numTinyAllocations;
            NumSmallAllocations = numSmallAllocations;
            NumNormalAllocations = numNormalAllocations;
            NumHugeAllocations = numHugeAllocations;
            NumDeallocations = numDeallocations;
            NumTinyDeallocations = numTinyDeallocations;
            NumSmallDeallocations = numSmallDeallocations;
            NumNormalDeallocations = numNormalDeallocations;
            NumHugeDeallocations = numHugeDeallocations;
            NumActiveAllocations = numActiveAllocations;
            NumActiveTinyAllocations = numActiveTinyAllocations;
            NumActiveSmallAllocations = numActiveSmallAllocations;
            NumActiveNormalAllocations = numActiveNormalAllocations;
            NumActiveHugeAllocations = numActiveHugeAllocations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numTinySubpages")]
        public int? NumTinySubpages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numSmallSubpages")]
        public int? NumSmallSubpages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numChunkLists")]
        public int? NumChunkLists { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tinySubpages")]
        public IList<PoolSubpageStats> TinySubpages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "smallSubpages")]
        public IList<PoolSubpageStats> SmallSubpages { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chunkLists")]
        public IList<PoolChunkListStats> ChunkLists { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numAllocations")]
        public long? NumAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numTinyAllocations")]
        public long? NumTinyAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numSmallAllocations")]
        public long? NumSmallAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numNormalAllocations")]
        public long? NumNormalAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numHugeAllocations")]
        public long? NumHugeAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numDeallocations")]
        public long? NumDeallocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numTinyDeallocations")]
        public long? NumTinyDeallocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numSmallDeallocations")]
        public long? NumSmallDeallocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numNormalDeallocations")]
        public long? NumNormalDeallocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numHugeDeallocations")]
        public long? NumHugeDeallocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numActiveAllocations")]
        public long? NumActiveAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numActiveTinyAllocations")]
        public long? NumActiveTinyAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numActiveSmallAllocations")]
        public long? NumActiveSmallAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numActiveNormalAllocations")]
        public long? NumActiveNormalAllocations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "numActiveHugeAllocations")]
        public long? NumActiveHugeAllocations { get; set; }

    }
}
