// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PoolChunkStats
    {
        /// <summary>
        /// Initializes a new instance of the PoolChunkStats class.
        /// </summary>
        public PoolChunkStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PoolChunkStats class.
        /// </summary>
        public PoolChunkStats(int? usage = default(int?), int? chunkSize = default(int?), int? freeBytes = default(int?))
        {
            Usage = usage;
            ChunkSize = chunkSize;
            FreeBytes = freeBytes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public int? Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "chunkSize")]
        public int? ChunkSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "freeBytes")]
        public int? FreeBytes { get; set; }

    }
}
