// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PostSchemaPayload
    {
        /// <summary>
        /// Initializes a new instance of the PostSchemaPayload class.
        /// </summary>
        public PostSchemaPayload()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostSchemaPayload class.
        /// </summary>
        public PostSchemaPayload(string type = default(string), string schema = default(string), IDictionary<string, string> properties = default(IDictionary<string, string>))
        {
            Type = type;
            Schema = schema;
            Properties = properties;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "schema")]
        public string Schema { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "properties")]
        public IDictionary<string, string> Properties { get; set; }

    }
}
