// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostSchemaResponse
    {
        /// <summary>
        /// Initializes a new instance of the PostSchemaResponse class.
        /// </summary>
        public PostSchemaResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostSchemaResponse class.
        /// </summary>
        public PostSchemaResponse(object version = default(object))
        {
            Version = version;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public object Version { get; set; }

    }
}
