// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ResourceDescription
    {
        /// <summary>
        /// Initializes a new instance of the ResourceDescription class.
        /// </summary>
        public ResourceDescription()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceDescription class.
        /// </summary>
        public ResourceDescription(int? usagePct = default(int?), IDictionary<string, ResourceUsage> resourceUsage = default(IDictionary<string, ResourceUsage>))
        {
            UsagePct = usagePct;
            ResourceUsage = resourceUsage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usagePct")]
        public int? UsagePct { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceUsage")]
        public IDictionary<string, ResourceUsage> ResourceUsage { get; set; }

    }
}
