// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RetentionPolicies
    {
        /// <summary>
        /// Initializes a new instance of the RetentionPolicies class.
        /// </summary>
        public RetentionPolicies()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RetentionPolicies class.
        /// </summary>
        public RetentionPolicies(int? retentionTimeInMinutes = default(int?), long? retentionSizeInMB = default(long?))
        {
            RetentionTimeInMinutes = retentionTimeInMinutes;
            RetentionSizeInMB = retentionSizeInMB;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retentionTimeInMinutes")]
        public int? RetentionTimeInMinutes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "retentionSizeInMB")]
        public long? RetentionSizeInMB { get; set; }

    }
}
