<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFrameworks>net5.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
    
  <ItemGroup>
      <PackageReference Include="Akka" />
      <PackageReference Include="DotNetty.Buffers" />
      <PackageReference Include="DotNetty.Codecs" />
      <PackageReference Include="DotNetty.Common" />
      <Using Include="Akka.Event" />
    <PackageReference Include="K4os.Compression.LZ4" />
    <PackageReference Include="Microsoft.IO.RecyclableMemoryStream" />
    <PackageReference Include="SharpZipLib" />
    <PackageReference Include="Snappy.Standard" />
    <PackageReference Include="zlib.net-mutliplatform" />
    <PackageReference Include="ZstdNet" />
    <PackageReference Include="protobuf-net" />
    <PackageReference Include="Google.Protobuf" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\SharpPulsar.API\SharpPulsar.API.csproj" />
    <ProjectReference Include="..\SharpPulsar.Shared\SharpPulsar.Shared.csproj" />
  </ItemGroup>

</Project>
