// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AuthPolicies
    {
        /// <summary>
        /// Initializes a new instance of the AuthPolicies class.
        /// </summary>
        public AuthPolicies()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AuthPolicies class.
        /// </summary>
        public AuthPolicies(IDictionary<string, IList<string>> namespaceAuth = default(IDictionary<string, IList<string>>), IDictionary<string, IDictionary<string, IList<string>>> destinationAuth = default(IDictionary<string, IDictionary<string, IList<string>>>), IDictionary<string, IList<string>> subscriptionAuthRoles = default(IDictionary<string, IList<string>>))
        {
            NamespaceAuth = namespaceAuth;
            DestinationAuth = destinationAuth;
            SubscriptionAuthRoles = subscriptionAuthRoles;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "namespace_auth")]
        public IDictionary<string, IList<string>> NamespaceAuth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destination_auth")]
        public IDictionary<string, IDictionary<string, IList<string>>> DestinationAuth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscription_auth_roles")]
        public IDictionary<string, IList<string>> SubscriptionAuthRoles { get; set; }

    }
}
