// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class BookieAffinityGroupData
    {
        /// <summary>
        /// Initializes a new instance of the BookieAffinityGroupData class.
        /// </summary>
        public BookieAffinityGroupData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BookieAffinityGroupData class.
        /// </summary>
        public BookieAffinityGroupData(string bookkeeperAffinityGroupPrimary = default(string), string bookkeeperAffinityGroupSecondary = default(string))
        {
            BookkeeperAffinityGroupPrimary = bookkeeperAffinityGroupPrimary;
            BookkeeperAffinityGroupSecondary = bookkeeperAffinityGroupSecondary;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookkeeperAffinityGroupPrimary")]
        public string BookkeeperAffinityGroupPrimary { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookkeeperAffinityGroupSecondary")]
        public string BookkeeperAffinityGroupSecondary { get; set; }

    }
}
