// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CursorDetails
    {
        /// <summary>
        /// Initializes a new instance of the CursorDetails class.
        /// </summary>
        public CursorDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CursorDetails class.
        /// </summary>
        public CursorDetails(long? cursorBacklog = default(long?), long? cursorLedgerId = default(long?))
        {
            CursorBacklog = cursorBacklog;
            CursorLedgerId = cursorLedgerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursorBacklog")]
        public long? CursorBacklog { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cursorLedgerId")]
        public long? CursorLedgerId { get; set; }

    }
}
