// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The data of a failure domain configuration in a cluster
    /// </summary>
    public partial class FailureDomain
    {
        /// <summary>
        /// Initializes a new instance of the FailureDomain class.
        /// </summary>
        public FailureDomain()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FailureDomain class.
        /// </summary>
        /// <param name="brokers">The collection of brokers in the same failure
        /// domain</param>
        public FailureDomain(IList<string> brokers = default(IList<string>))
        {
            Brokers = brokers;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the collection of brokers in the same failure domain
        /// </summary>
        [JsonProperty(PropertyName = "brokers")]
        public IList<string> Brokers { get; set; }

    }
}
