// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InternalConfigurationData
    {
        /// <summary>
        /// Initializes a new instance of the InternalConfigurationData class.
        /// </summary>
        public InternalConfigurationData()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InternalConfigurationData class.
        /// </summary>
        public InternalConfigurationData(string zookeeperServers = default(string), string configurationStoreServers = default(string), string ledgersRootPath = default(string), string stateStorageServiceUrl = default(string))
        {
            ZookeeperServers = zookeeperServers;
            ConfigurationStoreServers = configurationStoreServers;
            LedgersRootPath = ledgersRootPath;
            StateStorageServiceUrl = stateStorageServiceUrl;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "zookeeperServers")]
        public string ZookeeperServers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configurationStoreServers")]
        public string ConfigurationStoreServers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ledgersRootPath")]
        public string LedgersRootPath { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stateStorageServiceUrl")]
        public string StateStorageServiceUrl { get; set; }

    }
}
