// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LedgerInfo
    {
        /// <summary>
        /// Initializes a new instance of the LedgerInfo class.
        /// </summary>
        public LedgerInfo()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LedgerInfo class.
        /// </summary>
        public LedgerInfo(long? ledgerId = default(long?), long? entries = default(long?), long? size = default(long?), bool? offloaded = default(bool?))
        {
            LedgerId = ledgerId;
            Entries = entries;
            Size = size;
            Offloaded = offloaded;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ledgerId")]
        public long? LedgerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entries")]
        public long? Entries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public long? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "offloaded")]
        public bool? Offloaded { get; set; }

    }
}
