// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LedgerDetails
    {
        /// <summary>
        /// Initializes a new instance of the LedgerDetails class.
        /// </summary>
        public LedgerDetails()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LedgerDetails class.
        /// </summary>
        public LedgerDetails(long? entries = default(long?), long? timestamp = default(long?), long? size = default(long?), long? ledgerId = default(long?))
        {
            Entries = entries;
            Timestamp = timestamp;
            Size = size;
            LedgerId = ledgerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "entries")]
        public long? Entries { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public long? Timestamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Size")]
        public long? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ledgerId")]
        public long? LedgerId { get; set; }

    }
}
