// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class NamespaceOwnershipStatus
    {
        /// <summary>
        /// Initializes a new instance of the NamespaceOwnershipStatus class.
        /// </summary>
        public NamespaceOwnershipStatus()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NamespaceOwnershipStatus class.
        /// </summary>
        /// <param name="brokerAssignment">Possible values include: 'primary',
        /// 'secondary', 'shared'</param>
        public NamespaceOwnershipStatus(string brokerAssignment = default(string), bool? isControlled = default(bool?), bool? isActive = default(bool?))
        {
            BrokerAssignment = brokerAssignment;
            IsControlled = isControlled;
            IsActive = isActive;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets possible values include: 'primary', 'secondary',
        /// 'shared'
        /// </summary>
        [JsonProperty(PropertyName = "broker_assignment")]
        public string BrokerAssignment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_controlled")]
        public bool? IsControlled { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_active")]
        public bool? IsActive { get; set; }

    }
}
