// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class NonPersistentPublisherStats
    {
        /// <summary>
        /// Initializes a new instance of the NonPersistentPublisherStats
        /// class.
        /// </summary>
        public NonPersistentPublisherStats()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the NonPersistentPublisherStats
        /// class.
        /// </summary>
        public NonPersistentPublisherStats(double? msgRateIn = default(double?), double? msgThroughputIn = default(double?), double? averageMsgSize = default(double?), long? producerId = default(long?), IDictionary<string, string> metadata = default(IDictionary<string, string>), double? msgDropRate = default(double?), string address = default(string), string producerName = default(string), string connectedSince = default(string), string clientVersion = default(string))
        {
            MsgRateIn = msgRateIn;
            MsgThroughputIn = msgThroughputIn;
            AverageMsgSize = averageMsgSize;
            ProducerId = producerId;
            Metadata = metadata;
            MsgDropRate = msgDropRate;
            Address = address;
            ProducerName = producerName;
            ConnectedSince = connectedSince;
            ClientVersion = clientVersion;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msgRateIn")]
        public double? MsgRateIn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msgThroughputIn")]
        public double? MsgThroughputIn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "averageMsgSize")]
        public double? AverageMsgSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "producerId")]
        public long? ProducerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "metadata")]
        public IDictionary<string, string> Metadata { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "msgDropRate")]
        public double? MsgDropRate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "producerName")]
        public string ProducerName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "connectedSince")]
        public string ConnectedSince { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientVersion")]
        public string ClientVersion { get; set; }

    }
}
