// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PersistencePolicies
    {
        /// <summary>
        /// Initializes a new instance of the PersistencePolicies class.
        /// </summary>
        public PersistencePolicies()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PersistencePolicies class.
        /// </summary>
        public PersistencePolicies(int? bookkeeperEnsemble = default(int?), int? bookkeeperWriteQuorum = default(int?), int? bookkeeperAckQuorum = default(int?), double? managedLedgerMaxMarkDeleteRate = default(double?))
        {
            BookkeeperEnsemble = bookkeeperEnsemble;
            BookkeeperWriteQuorum = bookkeeperWriteQuorum;
            BookkeeperAckQuorum = bookkeeperAckQuorum;
            ManagedLedgerMaxMarkDeleteRate = managedLedgerMaxMarkDeleteRate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookkeeperEnsemble")]
        public int? BookkeeperEnsemble { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookkeeperWriteQuorum")]
        public int? BookkeeperWriteQuorum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bookkeeperAckQuorum")]
        public int? BookkeeperAckQuorum { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "managedLedgerMaxMarkDeleteRate")]
        public double? ManagedLedgerMaxMarkDeleteRate { get; set; }

    }
}
