// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PublishRate
    {
        /// <summary>
        /// Initializes a new instance of the PublishRate class.
        /// </summary>
        public PublishRate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PublishRate class.
        /// </summary>
        public PublishRate(int? publishThrottlingRateInMsg = default(int?), long? publishThrottlingRateInByte = default(long?))
        {
            PublishThrottlingRateInMsg = publishThrottlingRateInMsg;
            PublishThrottlingRateInByte = publishThrottlingRateInByte;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publishThrottlingRateInMsg")]
        public int? PublishThrottlingRateInMsg { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publishThrottlingRateInByte")]
        public long? PublishThrottlingRateInByte { get; set; }

    }
}
