// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace PulsarAdmin.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ResourceUnit
    {
        /// <summary>
        /// Initializes a new instance of the ResourceUnit class.
        /// </summary>
        public ResourceUnit()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ResourceUnit class.
        /// </summary>
        public ResourceUnit(string resourceId = default(string), ResourceDescription availableResource = default(ResourceDescription))
        {
            ResourceId = resourceId;
            AvailableResource = availableResource;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "resourceId")]
        public string ResourceId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "availableResource")]
        public ResourceDescription AvailableResource { get; set; }

    }
}
