name: Cancel
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: 19777845,19424828,19327380,19327055,11908337,11762375,5725340,22229939
          access_token: ${{ github.token }}