name: Cancel
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.7.0
        with:
          workflow_id: 5618468910,5618468911,5618468926,5618468886
          access_token: ${{ github.token }}