# https://api.github.com/repos/eaba/SharpPulsar/actions/workflows

name: Cancel
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.12.0
        with:
          workflow_id: 26218862,58515320,79616816,79616817,5740115
          access_token: ${{ github.token }}