# https://api.github.com/repos/eaba/SharpPulsar/actions/workflows

name: Cancel
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: 19424828
          access_token: ${{ github.token }}